# Configuration file of FAR training experiment
# ========== Cluster configuration ========== 
# IP address of the parameter server (need 1 GPU process)
ps_ip: 128.232.115.66
# <IP address of each worker>:[<# of available gpus processes on each gpu in this node>]
# Note that if we collocate ps and worker on same GPU, then we need to decrease this number of available processes on that GPU by 1
# E.g., master node has 4 available processes, then 1 for the ps, and worker should be set to: worker:3
worker_ips:
    - 128.232.115.0:[10,0,0]
    - 128.232.115.66:[10,10,10]
# Experiment path
exp_path: /nfs-share/ls985/FedScale/fedscale/cloud
# Entry function of executor and aggregator under $exp_path
executor_entry: execution/executor.py
aggregator_entry: aggregation/aggregator.py
# Authentication for ssh (unused if running locally)
auth:
    ssh_user: ""
    ssh_private_key: ~/.ssh/id_rsa
# Commands to run before we can indeed run FAR (in order)
setup_commands:
    - poetry shell
# ========== Additional job configuration ========== 
# Default parameters are specified in config_parser.py, wherein more description of the parameter can be found
job_conf: 
    - ps_port: 29502
    # Generate logs under this folder: log_path/job_name/time_stamp
    - job_name: openimage_multi_1+3
    # Path of log files
    - log_path: /nfs-share/ls985/FedScale/benchmark
    # Number of participants per round, we use K=100 in our paper, large K will be much slower
    - num_participants: 100
    # Dataset: openImg, google_speech, blog, shakespeare
    - data_set: openImg
    # Path of the dataset
    - data_dir: /datasets/FedScale/openImg
    # Allocation of data to each client, turn to iid setting if not provided
    - data_map_file: /datasets/FedScale/openImg/client_data_mapping/train.csv
    # Models: e.g., shufflenet_v2_x2_0, mobilenet_v2, resnet34, albert-base-v2, shakespeare
    - model: shufflenet_v2_x2_0
    # {"fed-yogi", "fed-prox", "fed-avg"}, "fed-avg" by default
    - gradient_policy: fed-yogi
    # How many rounds to run a testing on the testing set
    - eval_interval: 5002
    # Number of rounds to run this training. We use 1000 in our paper, while it may converge w/ ~400 rounds
    - rounds: 100
    # Remove clients w/ less than `filter_less` samples
    - filter_less: 21
    # Sets the `num_workers` parameter of the `torch.utils.data.DataLoader`
    - num_loaders: 1
    - yogi_eta: 3e-3 
    - yogi_tau: 1e-8
    # We are using epochs, so this is the number of epochs to run
    - local_steps: 1
    - learning_rate: 0.05
    - batch_size: 20
    - test_bsz: 20
